import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Experience: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>jordan hilado - experience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>experience</h1>
      </main>

      <footer className={styles.footer}>Last updated 9/5/2022</footer>
    </div>
  );
};

export default Experience;
