import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>jordan hilado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>jordan hilado</h1>

        <p className={styles.description}>
          i’m a junior at cal state long beach majoring in computer science. i
          enjoy building full-stack software applications. when i’m not coding,
          i’m either listening to podcasts, 3d printing, or playing sports like
          basketball or golf.
        </p>

        <div className={styles.grid}>
          <a href="/education" className={styles.card}>
            <h2>education</h2>
          </a>

          <a href="/experience" className={styles.card}>
            <h2>experience</h2>
          </a>

          <a href="/projects" className={styles.card}>
            <h2>projects</h2>
          </a>

          <a href="/skills" className={styles.card}>
            <h2>skills</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>Last updated 9/5/2022</footer>
    </div>
  );
};

export default Home;
